#!/usr/bin/env bash
# Script uses a while loop to print "Best School" 10 times and uses if else statements to modify the output

i=1
while (( i <= 10))
do
	if (( i == 4))
	then
		echo $"bad luck"
	elif (( i == 8 ))
	then
		echo $"good luck"
	else
		echo $"Best School"
	fi
	(( i++ ))
done
