#!/usr/bin/env bash
# script prints numbers 1 - 20 with case statements

i=1
while (( i <= 20 ))
do
	echo $i

	case $i in 
		4 )
			echo $"Bad luck in China";;
		9 )
			echo $"Bad luck in Japan";;
		17 )
			echo $"Bad luck in Italy";;

	esac
	(( i++ ))
done
